# Generated by Django 5.0.6 on 2024-06-25 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=45)),
                ('contraseña', models.CharField(max_length=45)),
            ],
        ),
    ]
