# Generated by Django 5.0.6 on 2024-06-26 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_camaras_camarashasevento_luminaria_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='evento',
            table='evento',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
    ]
