# Generated by Django 5.0.6 on 2024-09-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_evento_table_alter_usuario_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoreoServicioHasCamaras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'monitoreo_servicio_has_camaras',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='MonitoreroServicioHasCamaras',
        ),
    ]
