# Generated by Django 5.0.7 on 2024-10-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_monitoreoserviciohascamaras_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TanqueAguaNiveles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_maximo', models.IntegerField()),
                ('nivel_minimo', models.IntegerField()),
                ('altura', models.FloatField()),
                ('diametro', models.FloatField()),
            ],
            options={
                'db_table': 'tanque_agua_niveles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Temporizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispositivo', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_inicio', models.TimeField(blank=True, null=True)),
                ('fecha_cierre', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'temporizador',
                'managed': False,
            },
        ),
    ]
