# Generated by Django 5.0.7 on 2024-11-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_tanqueaguaniveles_temporizador'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporizadorLuminarias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispositivo', models.CharField(blank=True, max_length=50, null=True)),
                ('horario_inicio', models.TimeField(blank=True, null=True)),
                ('horario_cierre', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'temporizador_luminaria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TemporizadorRegado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispositivo', models.CharField(blank=True, max_length=50, null=True)),
                ('horario_inicio', models.TimeField(blank=True, null=True)),
                ('horario_cierre', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'temporizador_regado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TermostatoNiveles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispositivo', models.CharField(blank=True, max_length=50, null=True)),
                ('temperatura_deseada', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
            ],
            options={
                'db_table': 'termostato_niveles',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Temporizador',
        ),
    ]
